version: '2'
services:
  mysql_db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: koombea
      MYSQL_DATABASE: contacts_db
      MYSQL_USER: koombea
      MYSQL_PASSWORD: koombea
    volumes:
      - ./resources/contacts_db_initial_schema.sql:/docker-entrypoint-initdb.d/dump.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: on-failure
    environment:
      ENV: prod
    depends_on:
      - mysql_db
