"""initial revision

Revision ID: 0e042d8ba78d
Revises: 
Create Date: 2022-02-13 01:01:40.762348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e042d8ba78d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ON_HOLD', 'PROCESSING', 'FAILED', 'TERMINATED', name='uploadstatus'), nullable=False),
    sa.Column('successful_lines', sa.Integer(), nullable=True),
    sa.Column('failed_lines', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_name', sa.String(length=255), nullable=True),
    sa.Column('_birth_date', sa.DateTime(), nullable=True),
    sa.Column('_phone', sa.String(length=30), nullable=True),
    sa.Column('_address', sa.String(length=768), nullable=True),
    sa.Column('_credit_card', sa.String(length=25), nullable=True),
    sa.Column('_franchise', sa.String(length=25), nullable=True),
    sa.Column('_email', sa.String(length=255), nullable=True),
    sa.Column('_date_created', sa.DateTime(), nullable=True),
    sa.Column('_last_4', sa.String(length=4), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    op.drop_table('uploads')
    # ### end Alembic commands ###
